export const LIVE_CONTENT = [
  {
    id: 1,
    type: 'video' as const,
    videoUrl: 'qftWF0EW8_g',
    title: 'Behind the Design: Minimalist Modern Ceramic Vase Set',
    author: 'Studio Craft',
    authorAvatar: '/placeholder-user.jpg',
    likes: 2847,
    comments: 142,
    tags: ['Home', 'Design', 'Lighting'],
    productLink: '/product/modern-ceramic-vase-set',
    description: 'Discover the inspiration behind our best-selling minimalist desk lamp. Handcrafted with precision.',
  },
  {
    id: 2,
    type: 'video' as const,
    videoUrl: 'iNzlr5fVfog',
    title: 'The Art of Ceramics',
    author: 'Clay & Co',
    authorAvatar: '/placeholder-user.jpg',
    likes: 5231,
    comments: 289,
    tags: ['Craft', 'Artisan', 'Home'],
    productLink: '/product/ceramic-dinnerware-set',
    description: 'Watch our master ceramicist shape each piece by hand, bringing warmth to your morning ritual.',
  },
  {
    id: 3,
    type: 'video' as const,
    videoUrl: 'y6MK7hCkOC4',
    title: 'Crafted to Last leather goods',
    author: 'Heritage Goods',
    authorAvatar: '/placeholder-user.jpg',
    likes: 3912,
    comments: 198,
    tags: ['Fashion', 'Leather', 'Craftsmanship'],
    productLink: '/product/leather-jacket',
    description: 'Every stitch tells a story. See how we craft leather goods that age beautifully with you.',
  },
  {
    id: 4,
    type: 'video' as const,
    videoUrl: 'HnzWpWOrqdU',
    title: 'Sustainable Style',
    author: 'Eco Fashion',
    authorAvatar: '/placeholder-user.jpg',
    likes: 4567,
    comments: 321,
    tags: ['Fashion', 'Sustainable', 'Design'],
    productLink: '/articles/30',
    description: 'Fashion that respects the planet. Explore our process from organic materials to finished garments.',
  },
  {
    id: 5,
    type: 'video' as const,
    videoUrl: 'zvikRg8ztC8',
    title: 'Tech That Inspires',
    author: 'Modern Tech',
    authorAvatar: '/placeholder-user.jpg',
    likes: 6843,
    comments: 412,
    tags: ['Technology', 'Innovation', 'Design'],
    productLink: '/product/wireless-earbuds-pro',
    description: 'Unbox innovation. See how cutting-edge technology meets timeless design.',
  },
];
